### PR TITLE
AB#2766 africaTalks API integration

### PR DESCRIPTION
**Pull request by jannisvisser**

### CODE REVIEW

**Comment by jannisvisser** [comment]
I have put the testing code in app.controller.ts for now, because that was easiest to test, and this PR is not meant for merging now anyway. Once we will decide to actually integrate we can move the code to the appropriate place.

**Comment by elwinschmitz** [comment]
@jannisvisser You could convert this PR to "draft", I think.

**Comment by jannisvisser** [comment]
@elwinschmitz done.

**Comment by jannisvisser** [comment]
This was just sample integration, and is already really integrated via other PR's. This one can be closed.

**Pull request closed without merging**
