### PR TITLE
AB#3747

### PR DESCRIPTION
**Pull request by omendram**
Need to add env variables for Referral App

### CODE REVIEW

**Comment by elwinschmitz** [comment]
@omendram These changes: https://github.com/global-121/121-platform/pull/1312/files need to be applied for the Referral-app as well then.

**Comment by omendram** [comment]
> @omendram These changes: https://github.com/global-121/121-platform/pull/1312/files need to be applied for the Referral-app as well then.

I have added changed to env.example and environment.ts file, however we'd still need to add values to .env file.

**Comment by elwinschmitz** [comment]
@omendram Is it the same value for all interfaces? Or has each interface its own iKey?

**Comment by omendram** [comment]
> @omendram Is it the same value for all interfaces? Or has each interface its own iKey?

It will be the same value for all, however it has changed from the old one. Can be accessed in azure portal under overview of 121-application-insights resource.

**Review by elwinschmitz — APPROVED** [review]

**Pull request merged**
