### PR TITLE
chore: add instance/version endpoint to mock-service

### PR DESCRIPTION
**Pull request by aberonni**
[AB#28880](https://dev.azure.com/redcrossnl/7d17f2a9-3f18-40f1-8c29-98568fbca7e4/_workitems/edit/28880)

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] I have added tests wherever relevant
- [x] I have made sure that all automated checks pass before requesting a review
- [x] I do not need any deviation from our PR guidelines

### CODE REVIEW

**Review by elwinschmitz — APPROVED** [review]

**Review by elwinschmitz — CHANGES_REQUESTED** [review]
Oh, wait.

The magic that happens in `package.json` in the 121-service also needs to be used here...

**Comment by elwinschmitz** [comment]
This magic: https://github.com/global-121/121-platform/blob/main/services/121-service/package.json#L15-L16

It needs to grab the version-number from the build (text-)file at start-up/build. (I'm not sure which of these 2 is _really_ used... but I guess its copied to the build-step out of caution(?) )

**Comment by elwinschmitz** [comment]
This new endpoint could also be used as a 'healthcheck' maybe.. (for lack of any better alternative):

https://github.com/global-121/121-platform/blob/main/services/docker-compose.yml#L47-L48

**Comment by elwinschmitz** [comment]
> https://github.com/global-121/121-platform/blob/main/services/docker-compose.yml#L47-L48

Also about that line; we should make that port-number configurable; like how `PORT_121_SERVICE` is handled.

**Review by arsforza — APPROVED** [review]

**Pull request merged**
