### PR TITLE
add workflow update translations

### PR DESCRIPTION
**Pull request by jmargutt**

### CODE REVIEW

**Comment by elwinschmitz** [comment]
Just a note-to-self / for reference:

Handling the "committing the changes" can be done without yet another external workflow,
see similar steps in: https://github.com/rodekruis/helpful-information/blob/main/.github/workflows/upgrade-dependencies.yml#L53-L71

**Comment by elwinschmitz** [comment]
Relevant XKCD:
https://xkcd.com/1319/

XKCD 1319

:D

**Comment by aberonni** [comment]
Hey @jmargutt @elwinschmitz is this PR still relevant? I see there hasn't been any activity here in a while.

**Comment by aberonni** [comment]
I'm closing this given that it hasn't received any activity in a while. @elwinschmitz @tijsziere feel free to add something to the backlog if this is still somewhat relevant (especially for Portalicious).

**Pull request closed without merging**
