### PR TITLE
Add CSV file with test registrations

### PR DESCRIPTION
**Pull request by diderikvw**
## Describe your changes

Add CSV file with test registrations for OCW without referenceids, so they do not result in duplicate externalReference when using them on Intersolve Test/Staging Env.

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] I have added tests wherever relevant
- [ ] I have made sure that all automated checks pass before requesting a review
- [ ] I do not need any deviation from our PR guidelines

### CODE REVIEW

**Comment by diderikvw** [comment]
Hi @PeterSmallenbroek , can you review this one?
Maybe we need help from Dom, since I accidentally did a merge instead of a rebase. No idea how to fix this.

**Comment by RubenGeo** [comment]
@diderikvw Is this PR still relevant or can we close it?

**Comment by diderikvw** [comment]
@RubenGeo  I think it is useful as per see above. I guess @PeterSmallenbroek did not get to reviewing yet.

**Comment by diderikvw** [comment]
Closing, put the CSV file in another branch :)

**Pull request closed without merging**
